package io.flowkit.codegen.generators

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.squareup.kotlinpoet.*
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import io.flowkit.codegen.models.*
import io.flowkit.codegen.annotations.TargetPlatform
import io.flowkit.codegen.annotations.DependencyInjection

/**
 * Generates MVI container implementations that work across Android and iOS platforms.
 *
 * The container is the heart of the MVI architecture - it manages state transitions,
 * processes intents, and emits side effects in a thread-safe, reactive manner.
 *
 * This generator creates pure Kotlin code that works on all platforms while providing
 * platform-specific optimizations when beneficial.
 */
class MviContainerGenerator(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger
) {

    /**
     * Generates the complete MVI container infrastructure for the given metadata.
     * This includes the main container class and any platform-specific variants.
     */
    fun generate(metadata: MviMetadata) {
        val containerClassName = metadata.generationConfig.containerClassName
        logger.info("🏗️ FlowKit: Generating MVI container: $containerClassName")

        try {
            // Generate the core container (works on all platforms)
            generateCoreContainer(metadata)

            // Generate platform-specific optimizations if needed
            if (metadata.platformConfig.targets.contains(TargetPlatform.ANDROID)) {
                generateAndroidOptimizedContainer(metadata)
            }

            if (metadata.platformConfig.targets.contains(TargetPlatform.IOS)) {
                generateIosOptimizedContainer(metadata)
            }

            logger.info("✅ FlowKit: Successfully generated container for ${metadata.stateInfo.simpleName}")

        } catch (exception: Exception) {
            logger.error("❌ FlowKit: Failed to generate container: ${exception.message}")
            throw exception
        }
    }

    /**
     * Generates the core MVI container that works on all platforms.
     * This container follows pure MVI principles and uses only cross-platform APIs.
     */
    private fun generateCoreContainer(metadata: MviMetadata) {
        val containerClass = buildCoreContainerClass(metadata)

        val fileSpec = FileSpec.builder(
            packageName = metadata.generationConfig.outputPackage,
            fileName = metadata.generationConfig.containerClassName
        )
            .addFileComment("Generated by FlowKit CodeGen - Cross-platform MVI container")
            .addFileComment("Do not modify this file directly - it will be regenerated")
            .addImports(metadata)
            .addType(containerClass)
            .build()

        writeFile(fileSpec, metadata)
    }

    /**
     * Builds the core container class with all necessary components.
     */
    private fun buildCoreContainerClass(metadata: MviMetadata): TypeSpec {
        val stateType = ClassName(metadata.stateInfo.packageName, metadata.stateInfo.simpleName)
        val intentType = metadata.intentInfo?.let {
            ClassName(it.packageName, it.simpleName)
        } ?: UNIT
        val sideEffectType = metadata.sideEffectInfo?.let {
            ClassName(it.packageName, it.simpleName)
        } ?: UNIT

        return TypeSpec.classBuilder(metadata.generationConfig.containerClassName)
            .addKdoc(buildContainerKDoc(metadata))
            .addSuperinterface(buildMviContainerInterface(stateType, intentType, sideEffectType))
            .primaryConstructor(buildConstructor(metadata))
            .addProperties(buildProperties(metadata, stateType, sideEffectType))
            .addInitializerBlock(buildInitializer(metadata))
            .addFunctions(buildFunctions(metadata, stateType, intentType, sideEffectType))
            .build()
    }

    /**
     * Builds comprehensive KDoc documentation for the generated container.
     */
    private fun buildContainerKDoc(metadata: MviMetadata): CodeBlock {
        return CodeBlock.builder()
            .add("Generated MVI container for [${metadata.stateInfo.simpleName}].\n")
            .add("\n")
            .add("This container manages state transitions in a thread-safe manner following MVI principles:\n")
            .add("- State is immutable and flows unidirectionally\n")
            .add("- Intents are processed sequentially to avoid race conditions\n")
            .add("- Side effects are emitted as one-time events\n")
            .add("\n")
            .add("**Platform Compatibility:** ${metadata.platformConfig.targets.joinToString(", ")}\n")
            .add("**Dependency Injection:** ${metadata.diConfig.framework}\n")
            .add("**Thread Safety:** Guaranteed through coroutine-safe implementations\n")
            .add("\n")
            .add("@see ${metadata.stateInfo.simpleName}\n")
            .apply {
                metadata.intentInfo?.let { add("@see ${it.simpleName}\n") }
                metadata.sideEffectInfo?.let { add("@see ${it.simpleName}\n") }
            }
            .build()
    }

    /**
     * Builds the MviContainer interface with proper type parameters.
     */
    private fun buildMviContainerInterface(
        stateType: TypeName,
        intentType: TypeName,
        sideEffectType: TypeName
    ): ParameterizedTypeName {
        return ClassName("io.flowkit.core", "MviContainer")
            .parameterizedBy(stateType, intentType, sideEffectType)
    }

    /**
     * Builds the constructor with dependency injection support.
     */
    private fun buildConstructor(metadata: MviMetadata): FunSpec {
        val constructor = FunSpec.constructorBuilder()
            .addParameter("scope", ClassName("kotlinx.coroutines", "CoroutineScope"))

        // Add dependency injection parameters based on framework
        when (metadata.diConfig.framework) {
            DependencyInjection.KOIN -> {
                constructor.addParameter("koin", ClassName("org.koin.core", "Koin"))
            }
            DependencyInjection.HILT -> {
                // Hilt uses @Inject annotation instead of constructor parameters
            }
            DependencyInjection.KODEIN -> {
                constructor.addParameter("kodein", ClassName("org.kodein.di", "DI"))
            }
            else -> {
                // Manual DI - add repository parameter
                val repositoryType = guessRepositoryType(metadata)
                constructor.addParameter("repository", repositoryType)
            }
        }

        return constructor.build()
    }

    /**
     * Guesses the repository type based on the state class name.
     * This follows common naming conventions.
     */
    private fun guessRepositoryType(metadata: MviMetadata): ClassName {
        val stateClassName = metadata.stateInfo.simpleName
        val repositoryName = stateClassName
            .replace("State", "Repository")
            .replace("Screen", "")

        return ClassName(metadata.stateInfo.packageName, repositoryName)
    }

    /**
     * Builds all the properties needed for the MVI container.
     */
    private fun buildProperties(
        metadata: MviMetadata,
        stateType: TypeName,
        sideEffectType: TypeName
    ): List<PropertySpec> {
        val properties = mutableListOf<PropertySpec>()

        // Private mutable state
        properties.add(
            PropertySpec.builder(
                "_state",
                ClassName("kotlinx.coroutines.flow", "MutableStateFlow").parameterizedBy(stateType),
                KModifier.PRIVATE
            )
                .initializer("MutableStateFlow(${metadata.stateInfo.simpleName}())")
                .addKdoc("Internal mutable state. Access through [state] property.")
                .build()
        )

        // Public state flow
        properties.add(
            PropertySpec.builder(
                "state",
                ClassName("kotlinx.coroutines.flow", "StateFlow").parameterizedBy(stateType),
                KModifier.OVERRIDE
            )
                .initializer("_state.asStateFlow()")
                .addKdoc("Reactive state flow. Emits the current state and all subsequent state changes.")
                .build()
        )

        // Private side effects channel
        properties.add(
            PropertySpec.builder(
                "_sideEffects",
                ClassName("kotlinx.coroutines.flow", "MutableSharedFlow").parameterizedBy(sideEffectType),
                KModifier.PRIVATE
            )
                .initializer("""
                MutableSharedFlow(
                    replay = 0,
                    extraBufferCapacity = 64,
                    onBufferOverflow = kotlinx.coroutines.channels.BufferOverflow.DROP_OLDEST
                )
            """.trimIndent())
                .addKdoc("Internal side effects channel with buffer to prevent blocking.")
                .build()
        )

        // Public side effects flow
        properties.add(
            PropertySpec.builder(
                "sideEffects",
                ClassName("kotlinx.coroutines.flow", "Flow").parameterizedBy(sideEffectType),
                KModifier.OVERRIDE
            )
                .initializer("_sideEffects.asSharedFlow()")
                .addKdoc("One-time side effects flow. Each side effect is delivered exactly once.")
                .build()
        )

        // Intent processing channel
        properties.add(
            PropertySpec.builder(
                "_intentChannel",
                ClassName("kotlinx.coroutines.channels", "Channel")
                    .parameterizedBy(metadata.intentInfo?.let {
                        ClassName(it.packageName, it.simpleName)
                    } ?: UNIT),
                KModifier.PRIVATE
            )
                .initializer("Channel(Channel.UNLIMITED)")
                .addKdoc("Internal channel for sequential intent processing.")
                .build()
        )

        // Reducer instance
        properties.add(
            PropertySpec.builder(
                "reducer",
                ClassName(metadata.generationConfig.outputPackage, metadata.generationConfig.reducerClassName),
                KModifier.PRIVATE
            )
                .initializer(buildReducerInitializer(metadata))
                .addKdoc("Reducer instance for processing intents and updating state.")
                .build()
        )

        // Add logging property if enabled
        if (metadata.annotation.enableLogging) {
            properties.add(
                PropertySpec.builder(
                    "logger",
                    ClassName("io.flowkit.core", "FlowKitLogger"),
                    KModifier.PRIVATE
                )
                    .initializer("FlowKitLogger(\"${metadata.generationConfig.containerClassName}\")")
                    .addKdoc("Logger instance for debugging state transitions and side effects.")
                    .build()
            )
        }

        return properties
    }

    /**
     * Builds the reducer initializer based on dependency injection configuration.
     */
    private fun buildReducerInitializer(metadata: MviMetadata): String {
        return when (metadata.diConfig.framework) {
            DependencyInjection.KOIN -> {
                "${metadata.generationConfig.reducerClassName}(koin.get())"
            }
            DependencyInjection.KODEIN -> {
                "${metadata.generationConfig.reducerClassName}(kodein.instance())"
            }
            else -> {
                "${metadata.generationConfig.reducerClassName}(repository)"
            }
        }
    }

    /**
     * Builds the initializer block that sets up intent processing.
     */
    private fun buildInitializer(metadata: MviMetadata): CodeBlock {
        return CodeBlock.builder()
            .addStatement("// Set up sequential intent processing")
            .addStatement("_intentChannel.receiveAsFlow()")
            .indent()
            .addStatement(".onEach { intent ->")
            .indent()
            .apply {
                if (metadata.annotation.enableLogging) {
                    addStatement("logger.logIntent(intent, _state.value)")
                }
            }
            .addStatement("processIntentInternal(intent)")
            .unindent()
            .addStatement("}")
            .addStatement(".catch { throwable ->")
            .indent()
            .apply {
                if (metadata.annotation.enableLogging) {
                    addStatement("logger.logError(\"Error processing intent\", throwable)")
                } else {
                    addStatement("// Handle intent processing errors gracefully")
                    addStatement("// In production, consider reporting to crash analytics")
                }
            }
            .unindent()
            .addStatement("}")
            .addStatement(".launchIn(scope)")
            .unindent()
            .build()
    }

    /**
     * Builds all the functions for the MVI container.
     */
    private fun buildFunctions(
        metadata: MviMetadata,
        stateType: TypeName,
        intentType: TypeName,
        sideEffectType: TypeName
    ): List<FunSpec> {
        return listOf(
            buildProcessIntentFunction(metadata, intentType),
            buildProcessIntentInternalFunction(metadata, stateType, intentType, sideEffectType),
            buildCurrentStateFunction(stateType),
            buildCloseFunction()
        )
    }

    /**
     * Builds the public processIntent function.
     */
    private fun buildProcessIntentFunction(metadata: MviMetadata, intentType: TypeName): FunSpec {
        return FunSpec.builder("processIntent")
            .addModifiers(KModifier.OVERRIDE, KModifier.SUSPEND)
            .addParameter("intent", intentType)
            .addKdoc("""
                Processes an intent asynchronously and updates the state accordingly.
                
                This function is thread-safe and ensures intents are processed sequentially
                to avoid race conditions. The intent will be queued if the container is
                currently processing another intent.
                
                @param intent The intent to process
            """.trimIndent())
            .addCode(
                CodeBlock.builder()
                    .addStatement("_intentChannel.trySend(intent)")
                    .addStatement("    .onFailure { throwable ->")
                    .indent()
                    .apply {
                        if (metadata.annotation.enableLogging) {
                            addStatement("logger.logError(\"Failed to queue intent: \$intent\", throwable)")
                        }
                    }
                    .unindent()
                    .addStatement("    }")
                    .build()
            )
            .build()
    }

    /**
     * Builds the internal intent processing function.
     */
    private fun buildProcessIntentInternalFunction(
        metadata: MviMetadata,
        stateType: TypeName,
        intentType: TypeName,
        sideEffectType: TypeName
    ): FunSpec {
        return FunSpec.builder("processIntentInternal")
            .addModifiers(KModifier.PRIVATE, KModifier.SUSPEND)
            .addParameter("intent", intentType)
            .addKdoc("Internal function that actually processes the intent using the reducer.")
            .addCode(buildProcessIntentInternalBody(metadata))
            .build()
    }

    /**
     * Builds the body of the internal intent processing function.
     */
    private fun buildProcessIntentInternalBody(metadata: MviMetadata): CodeBlock {
        return CodeBlock.builder()
            .addStatement("try {")
            .indent()
            .addStatement("val currentState = _state.value")
            .addStatement("val result = reducer.reduce(currentState, intent)")
            .addStatement("")
            .addStatement("// Update state if it changed")
            .addStatement("if (result.newState != currentState) {")
            .indent()
            .addStatement("_state.value = result.newState")
            .apply {
                if (metadata.annotation.enableLogging) {
                    addStatement("logger.logStateChange(currentState, result.newState, intent)")
                }
            }
            .unindent()
            .addStatement("}")
            .addStatement("")
            .addStatement("// Emit side effects")
            .addStatement("result.sideEffects.forEach { sideEffect ->")
            .indent()
            .addStatement("_sideEffects.tryEmit(sideEffect)")
            .apply {
                if (metadata.annotation.enableLogging) {
                    addStatement("logger.logSideEffect(sideEffect, intent)")
                }
            }
            .unindent()
            .addStatement("}")
            .unindent()
            .addStatement("} catch (exception: Exception) {")
            .indent()
            .apply {
                if (metadata.annotation.enableLogging) {
                    addStatement("logger.logError(\"Reducer error for intent: \$intent\", exception)")
                } else {
                    addStatement("// Handle reducer errors gracefully")
                    addStatement("// Consider emitting an error side effect")
                }
            }
            .unindent()
            .addStatement("}")
            .build()
    }

    /**
     * Builds the currentState function.
     */
    private fun buildCurrentStateFunction(stateType: TypeName): FunSpec {
        return FunSpec.builder("currentState")
            .addModifiers(KModifier.OVERRIDE)
            .returns(stateType)
            .addKdoc("Returns the current state value synchronously.")
            .addStatement("return _state.value")
            .build()
    }

    /**
     * Builds the close function for proper resource cleanup.
     */
    private fun buildCloseFunction(): FunSpec {
        return FunSpec.builder("close")
            .addKdoc("""
                Closes the container and releases resources.
                
                This function should be called when the container is no longer needed
                to prevent memory leaks and ensure proper cleanup.
            """.trimIndent())
            .addCode(
                CodeBlock.builder()
                    .addStatement("_intentChannel.close()")
                    .build()
            )
            .build()
    }

    /**
     * Generates Android-specific optimizations for the MVI container.
     */
    private fun generateAndroidOptimizedContainer(metadata: MviMetadata) {
        if (!metadata.platformConfig.androidConfig?.generateViewModel!!) return

        val androidContainerClass = buildAndroidContainerClass(metadata)

        val fileSpec = FileSpec.builder(
            packageName = metadata.generationConfig.outputPackage,
            fileName = "${metadata.generationConfig.containerClassName}Android"
        )
            .addFileComment("Generated by FlowKit CodeGen - Android-optimized MVI container")
            .addImport("androidx.lifecycle", "ViewModel", "viewModelScope")
            .addImport("kotlinx.coroutines", "launch")
            .addType(androidContainerClass)
            .build()

        writeFile(fileSpec, metadata, "Android")
    }

    /**
     * Builds the Android-optimized container class.
     */
    private fun buildAndroidContainerClass(metadata: MviMetadata): TypeSpec {
        return TypeSpec.classBuilder("${metadata.generationConfig.containerClassName}Android")
            .superclass(ClassName("androidx.lifecycle", "ViewModel"))
            .addKdoc("Android-optimized MVI container with ViewModel integration.")
            .primaryConstructor(buildAndroidConstructor(metadata))
            .addProperty(buildContainerProperty(metadata))
            .addFunctions(buildAndroidFunctions(metadata))
            .apply {
                // Add Hilt annotation if using Hilt
                if (metadata.diConfig.framework == DependencyInjection.HILT) {
                    addAnnotation(ClassName("dagger.hilt.android.lifecycle", "HiltViewModel"))
                }
            }
            .build()
    }

    /**
     * Builds the Android constructor with proper DI annotations.
     */
    private fun buildAndroidConstructor(metadata: MviMetadata): FunSpec {
        val constructor = FunSpec.constructorBuilder()

        when (metadata.diConfig.framework) {
            DependencyInjection.HILT -> {
                constructor.addAnnotation(ClassName("javax.inject", "Inject"))
                val repositoryType = guessRepositoryType(metadata)
                constructor.addParameter("repository", repositoryType)
            }
            DependencyInjection.KOIN -> {
                // Koin integration handled differently in Android
            }
            else -> {
                val repositoryType = guessRepositoryType(metadata)
                constructor.addParameter("repository", repositoryType)
            }
        }

        return constructor.build()
    }

    /**
     * Builds the container property for the Android wrapper.
     */
    private fun buildContainerProperty(metadata: MviMetadata): PropertySpec {
        return PropertySpec.builder(
            "container",
            ClassName(metadata.generationConfig.outputPackage, metadata.generationConfig.containerClassName),
            KModifier.PRIVATE
        )
            .initializer(buildAndroidContainerInitializer(metadata))
            .build()
    }

    /**
     * Builds the container initializer for Android.
     */
    private fun buildAndroidContainerInitializer(metadata: MviMetadata): String {
        return when (metadata.diConfig.framework) {
            DependencyInjection.HILT -> {
                "${metadata.generationConfig.containerClassName}(viewModelScope, repository)"
            }
            DependencyInjection.KOIN -> {
                "${metadata.generationConfig.containerClassName}(viewModelScope, get())"
            }
            else -> {
                "${metadata.generationConfig.containerClassName}(viewModelScope, repository)"
            }
        }
    }

    /**
     * Builds Android-specific functions that delegate to the container.
     */
    private fun buildAndroidFunctions(metadata: MviMetadata): List<FunSpec> {
        val stateType = ClassName(metadata.stateInfo.packageName, metadata.stateInfo.simpleName)
        val intentType = metadata.intentInfo?.let {
            ClassName(it.packageName, it.simpleName)
        } ?: UNIT
        val sideEffectType = metadata.sideEffectInfo?.let {
            ClassName(it.packageName, it.simpleName)
        } ?: UNIT

        return listOf(
            // State property
            PropertySpec.builder(
                "state",
                ClassName("kotlinx.coroutines.flow", "StateFlow").parameterizedBy(stateType)
            )
                .initializer("container.state")
                .build().let { property ->
                    FunSpec.getterBuilder()
                        .addStatement("return container.state")
                        .build()
                },

            // Side effects property
            PropertySpec.builder(
                "sideEffects",
                ClassName("kotlinx.coroutines.flow", "Flow").parameterizedBy(sideEffectType)
            )
                .initializer("container.sideEffects")
                .build().let { property ->
                    FunSpec.getterBuilder()
                        .addStatement("return container.sideEffects")
                        .build()
                },

            // Process intent function
            FunSpec.builder("processIntent")
                .addParameter("intent", intentType)
                .addCode(
                    CodeBlock.builder()
                        .addStatement("viewModelScope.launch {")
                        .indent()
                        .addStatement("container.processIntent(intent)")
                        .unindent()
                        .addStatement("}")
                        .build()
                )
                .build(),

            // Current state function
            FunSpec.builder("currentState")
                .returns(stateType)
                .addStatement("return container.currentState()")
                .build(),

            // Override onCleared for proper cleanup
            FunSpec.builder("onCleared")
                .addModifiers(KModifier.OVERRIDE)
                .addStatement("super.onCleared()")
                .addStatement("container.close()")
                .build()
        )
    }

    /**
     * Generates iOS-specific optimizations for the MVI container.
     */
    private fun generateIosOptimizedContainer(metadata: MviMetadata) {
        val iosContainerClass = buildIosContainerClass(metadata)

        val fileSpec = FileSpec.builder(
            packageName = metadata.generationConfig.outputPackage,
            fileName = "${metadata.generationConfig.containerClassName}Ios"
        )
            .addFileComment("Generated by FlowKit CodeGen - iOS-optimized MVI container")
            .addFileComment("Optimized for memory management and Swift interoperability")
            .addType(iosContainerClass)
            .build()

        writeFile(fileSpec, metadata, "Ios")
    }

    /**
     * Builds the iOS-optimized container class.
     */
    private fun buildIosContainerClass(metadata: MviMetadata): TypeSpec {
        val baseContainerType = ClassName(metadata.generationConfig.outputPackage, metadata.generationConfig.containerClassName)

        return TypeSpec.classBuilder("${metadata.generationConfig.containerClassName}Ios")
            .superclass(baseContainerType)
            .addKdoc("""
                iOS-optimized MVI container with memory management optimizations.
                
                This class extends the base container with iOS-specific optimizations:
                - Memory-efficient state handling
                - Swift interoperability improvements
                - iOS lifecycle awareness
            """.trimIndent())
            .primaryConstructor(buildIosConstructor(metadata))
            .addFunctions(buildIosFunctions(metadata))
            .build()
    }

    /**
     * Builds the iOS constructor.
     */
    private fun buildIosConstructor(metadata: MviMetadata): FunSpec {
        return FunSpec.constructorBuilder()
            .addParameter("scope", ClassName("kotlinx.coroutines", "CoroutineScope"))
            .apply {
                when (metadata.diConfig.framework) {
                    DependencyInjection.KOIN -> {
                        addParameter("koin", ClassName("org.koin.core", "Koin"))
                    }
                    else -> {
                        val repositoryType = guessRepositoryType(metadata)
                        addParameter("repository", repositoryType)
                    }
                }
            }
            .build()
    }

    /**
     * Builds iOS-specific functions with memory optimizations.
     */
    private fun buildIosFunctions(metadata: MviMetadata): List<FunSpec> {
        return listOf(
            // Memory cleanup function for iOS
            FunSpec.builder("cleanup")
                .addKdoc("Performs iOS-specific memory cleanup.")
                .addCode(
                    CodeBlock.builder()
                        .addStatement("// Perform iOS-specific cleanup")
                        .addStatement("close()")
                        .addStatement("// Additional iOS memory management if needed")
                        .build()
                )
                .build()
        )
    }

    /**
     * Adds necessary imports to the file spec.
     */
    private fun FileSpec.Builder.addImports(metadata: MviMetadata): FileSpec.Builder {
        return apply {
            metadata.generationConfig.requiredImports.forEach { import ->
                val parts = import.split(".")
                if (parts.size >= 2) {
                    val packageName = parts.dropLast(1).joinToString(".")
                    val className = parts.last()
                    addImport(packageName, className)
                }
            }
        }
    }

    /**
     * Writes the generated file to the appropriate output directory.
     */
    private fun writeFile(fileSpec: FileSpec, metadata: MviMetadata, suffix: String = "") {
        try {
            val fileName = if (suffix.isNotEmpty()) {
                "${metadata.generationConfig.containerClassName}$suffix"
            } else {
                metadata.generationConfig.containerClassName
            }

            // Create the file using KSP CodeGenerator
            val file = codeGenerator.createNewFile(
                dependencies = Dependencies(false), // No dependencies on source files
                packageName = metadata.generationConfig.outputPackage,
                fileName = fileName
            )

            // Write the content to the file
            file.bufferedWriter().use { writer ->
                fileSpec.writeTo(writer)
            }

            logger.info("📝 FlowKit: Generated file: $fileName.kt")

        } catch (exception: Exception) {
            logger.error("❌ FlowKit: Failed to write file: ${exception.message}")
            throw exception
        }
    }
}