package io.flowkit.codegen.generators

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.ParameterizedTypeName
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.UNIT
import io.flowkit.codegen.annotations.DependencyInjection
import io.flowkit.codegen.models.MviMetadata

/**
 * Generates MVI reducer implementations with intelligent business logic scaffolding.
 *
 * The reducer is the pure function heart of MVI - it takes the current state and an intent,
 * then returns the new state and any side effects. This generator creates reducer
 * implementations that:
 *
 * - Follow functional programming principles (pure functions, immutability)
 * - Provide scaffolding for common business logic patterns
 * - Include comprehensive documentation and examples
 * - Support dependency injection for accessing repositories and services
 * - Generate platform-agnostic code that works everywhere
 */
class MviReducerGenerator(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger
) {

    /**
     * Generates the reducer implementation for the given MVI metadata.
     */
    fun generate(metadata: MviMetadata) {
        val reducerClassName = metadata.generationConfig.reducerClassName
        logger.info("⚙️ FlowKit: Generating reducer: $reducerClassName")

        try {
            val reducerClass = buildReducerClass(metadata)

            val fileSpec = FileSpec.builder(
                packageName = metadata.generationConfig.outputPackage,
                fileName = metadata.generationConfig.reducerClassName
            )
                .addFileComment("Generated by FlowKit CodeGen - MVI Reducer")
                .addFileComment("This reducer follows functional programming principles")
                .addFileComment("Modify the TODO sections to implement your business logic")
                .addReducerImports(metadata)
                .addType(reducerClass)
                .build()

            writeFile(fileSpec, metadata)
            logger.info("✅ FlowKit: Successfully generated reducer for ${metadata.stateInfo.simpleName}")

        } catch (exception: Exception) {
            logger.error("❌ FlowKit: Failed to generate reducer: ${exception.message}")
            throw exception
        }
    }

    /**
     * Builds the complete reducer class with business logic scaffolding.
     */
    private fun buildReducerClass(metadata: MviMetadata): TypeSpec {
        val stateType = ClassName(metadata.stateInfo.packageName, metadata.stateInfo.simpleName)
        val intentType = metadata.intentInfo?.let {
            ClassName(it.packageName, it.simpleName)
        } ?: UNIT
        val sideEffectType = metadata.sideEffectInfo?.let {
            ClassName(it.packageName, it.simpleName)
        } ?: UNIT

        return TypeSpec.classBuilder(metadata.generationConfig.reducerClassName)
            .addKdoc(buildReducerKDoc(metadata))
            .addSuperinterface(buildMviReducerInterface(stateType, intentType, sideEffectType))
            .primaryConstructor(buildReducerConstructor(metadata))
            .addProperties(buildReducerProperties(metadata))
            .addFunctions(buildReducerFunctions(metadata, stateType, intentType, sideEffectType))
            .build()
    }

    /**
     * Builds comprehensive KDoc for the reducer.
     */
    private fun buildReducerKDoc(metadata: MviMetadata): CodeBlock {
        return CodeBlock.builder()
            .add("Generated MVI reducer for [${metadata.stateInfo.simpleName}].\n")
            .add("\n")
            .add("This reducer implements the core business logic following MVI principles:\n")
            .add("\n")
            .add("**Key Principles:**\n")
            .add("- **Pure Functions:** No side effects, same input always produces same output\n")
            .add("- **Immutability:** State is never mutated, only copied with changes\n")
            .add("- **Predictability:** All state changes are explicit and traceable\n")
            .add("- **Testability:** Easy to unit test due to pure function nature\n")
            .add("\n")
            .add("**Implementation Guide:**\n")
            .add("1. Implement the TODO sections with your business logic\n")
            .add("2. Use `currentState.copy()` to create new state instances\n")
            .add("3. Return side effects for one-time events (navigation, dialogs, etc.)\n")
            .add("4. Keep reducers pure - use repositories for external data access\n")
            .add("\n")
            .add("**Example:**\n")
            .add("```kotlin\n")
            .add("is LoadUsers -> {\n")
            .add("    val newState = currentState.copy(isLoading = true, error = null)\n")
            .add("    val users = repository.getUsers() // Called via side effect or middleware\n")
            .add("    ReducerResult(newState, listOf(LoadUsersEffect))\n")
            .add("}\n")
            .add("```\n")
            .build()
    }

    /**
     * Builds the MviReducer interface with proper type parameters.
     */
    private fun buildMviReducerInterface(
        stateType: TypeName,
        intentType: TypeName,
        sideEffectType: TypeName
    ): ParameterizedTypeName {
        return ClassName("io.flowkit.core", "MviReducer")
            .parameterizedBy(stateType, intentType, sideEffectType)
    }

    /**
     * Builds the reducer constructor with dependency injection.
     */
    private fun buildReducerConstructor(metadata: MviMetadata): FunSpec {
        val constructor = FunSpec.constructorBuilder()

        // Add dependencies based on DI framework
        when (metadata.diConfig.framework) {
            DependencyInjection.KOIN -> {
                constructor.addParameter("koin", ClassName("org.koin.core", "Koin"))
            }

            DependencyInjection.HILT -> {
                constructor.addAnnotation(ClassName("javax.inject", "Inject"))
                addRepositoryParameter(constructor, metadata)
            }

            else -> {
                addRepositoryParameter(constructor, metadata)
            }
        }

        return constructor.build()
    }

    /**
     * Adds repository parameter to constructor for manual DI.
     */
    private fun addRepositoryParameter(constructor: FunSpec.Builder, metadata: MviMetadata) {
        val repositoryType = guessRepositoryType(metadata)
        constructor.addParameter("repository", repositoryType)
    }

    /**
     * Guesses the repository type based on naming conventions.
     */
    private fun guessRepositoryType(metadata: MviMetadata): ClassName {
        val stateClassName = metadata.stateInfo.simpleName
        val repositoryName = stateClassName
            .replace("State", "Repository")
            .replace("Screen", "")

        return ClassName(metadata.stateInfo.packageName, repositoryName)
    }

    /**
     * Builds properties for the reducer (mainly dependencies).
     */
    private fun buildReducerProperties(metadata: MviMetadata): List<PropertySpec> {
        val properties = mutableListOf<PropertySpec>()

        when (metadata.diConfig.framework) {
            DependencyInjection.KOIN -> {
                // Koin dependencies injected via lazy delegation
                properties.add(
                    PropertySpec.builder(
                        "repository",
                        guessRepositoryType(metadata),
                        KModifier.PRIVATE
                    )
                        .delegate("koin.get()")
                        .addKdoc("Repository dependency injected via Koin")
                        .build()
                )
            }

            else -> {
                // Direct constructor injection
                properties.add(
                    PropertySpec.builder(
                        "repository",
                        guessRepositoryType(metadata),
                        KModifier.PRIVATE
                    )
                        .initializer("repository")
                        .addKdoc("Repository dependency for accessing external data")
                        .build()
                )
            }
        }

        return properties
    }

    /**
     * Builds all functions for the reducer.
     */
    private fun buildReducerFunctions(
        metadata: MviMetadata,
        stateType: TypeName,
        intentType: TypeName,
        sideEffectType: TypeName
    ): List<FunSpec> {
        return listOf(
            buildReduceFunction(metadata, stateType, intentType, sideEffectType)
        )
    }

    /**
     * Builds the main reduce function with smart scaffolding.
     */
    private fun buildReduceFunction(
        metadata: MviMetadata,
        stateType: TypeName,
        intentType: TypeName,
        sideEffectType: TypeName
    ): FunSpec {
        val returnType = ClassName("io.flowkit.core", "ReducerResult")
            .parameterizedBy(stateType, sideEffectType)

        return FunSpec.builder("reduce")
            .addModifiers(KModifier.OVERRIDE, KModifier.SUSPEND)
            .addParameter("currentState", stateType)
            .addParameter("intent", intentType)
            .returns(returnType)
            .addKdoc(buildReduceFunctionKDoc())
            .addCode(buildReduceFunctionBody(metadata, stateType, sideEffectType))
            .build()
    }

    /**
     * Builds KDoc for the reduce function.
     */
    private fun buildReduceFunctionKDoc(): CodeBlock {
        return CodeBlock.builder()
            .add("Reduces the current state and intent to produce a new state and side effects.\n")
            .add("\n")
            .add("This is a pure function that should not perform any side effects directly.\n")
            .add("Instead, return side effects in the ReducerResult to be handled by the container.\n")
            .add("\n")
            .add("@param currentState The current state before processing the intent\n")
            .add("@param intent The intent to process\n")
            .add("@return ReducerResult containing the new state and any side effects\n")
            .build()
    }

    /**
     * Builds the body of the reduce function with intelligent scaffolding.
     */
    private fun buildReduceFunctionBody(
        metadata: MviMetadata,
        stateType: TypeName,
        sideEffectType: TypeName
    ): CodeBlock {
        val builder = CodeBlock.builder()

        builder.addStatement("return when (intent) {")
        builder.indent()

        // Generate scaffolding based on discovered Intent classes
        if (metadata.intentInfo?.isSealedClass == true) {
            generateIntentScaffolding(builder, metadata, stateType, sideEffectType)
        } else {
            generateGenericScaffolding(builder, metadata, stateType, sideEffectType)
        }

        builder.unindent()
        builder.addStatement("}")

        return builder.build()
    }

    /**
     * Generates scaffolding for sealed intent classes.
     */
    private fun generateIntentScaffolding(
        builder: CodeBlock.Builder,
        metadata: MviMetadata,
        stateType: TypeName,
        sideEffectType: TypeName
    ) {
        val intentInfo = metadata.intentInfo!!
        val intentClassName = intentInfo.simpleName

        // Generate common intent patterns
        generateLoadingIntentPattern(builder, intentClassName, stateType, sideEffectType)
        generateRefreshIntentPattern(builder, intentClassName, stateType, sideEffectType)
        generateErrorIntentPattern(builder, intentClassName, stateType, sideEffectType)
        generateSelectionIntentPattern(builder, intentClassName, stateType, sideEffectType)

        // TODO comment for additional intents
        builder.addStatement("// TODO: Implement additional intent handling")
        builder.addStatement("// Add your custom business logic here")
        builder.addStatement("")

        // Default case
        builder.addStatement("else -> {")
        builder.indent()
        builder.addStatement("// Unhandled intent - return current state unchanged")
        builder.addStatement("ReducerResult(currentState)")
        builder.unindent()
        builder.addStatement("}")
    }

    /**
     * Generates scaffolding for loading-type intents.
     */
    private fun generateLoadingIntentPattern(
        builder: CodeBlock.Builder,
        intentClassName: String,
        stateType: TypeName,
        sideEffectType: TypeName
    ) {
        // Common loading patterns
        val loadingIntents = listOf("Load", "LoadData", "LoadUsers", "LoadContent", "Fetch")

        loadingIntents.forEach { pattern ->
            builder.addStatement("is $intentClassName.$pattern -> {")
            builder.indent()
            builder.addStatement("// TODO: Implement loading logic")
            builder.addStatement("val newState = currentState.copy(")
            builder.indent()
            builder.addStatement("isLoading = true,")
            builder.addStatement("error = null")
            builder.unindent()
            builder.addStatement(")")
            builder.addStatement("")
            builder.addStatement("// Example: Trigger async loading via side effect")
            builder.addStatement(
                "// val sideEffects = listOf(${
                    intentClassName.replace(
                        "Intent",
                        "SideEffect"
                    )
                }.StartLoading)"
            )
            builder.addStatement("")
            builder.addStatement("ReducerResult(newState)")
            builder.unindent()
            builder.addStatement("}")
            builder.addStatement("")
        }
    }

    /**
     * Generates scaffolding for refresh-type intents.
     */
    private fun generateRefreshIntentPattern(
        builder: CodeBlock.Builder,
        intentClassName: String,
        stateType: TypeName,
        sideEffectType: TypeName
    ) {
        builder.addStatement("// is $intentClassName.Refresh -> {")
        builder.addStatement("//     // TODO: Implement refresh logic")
        builder.addStatement("//     val newState = currentState.copy(isLoading = true)")
        builder.addStatement("//     ReducerResult(newState)")
        builder.addStatement("// }")
        builder.addStatement("")
    }

    /**
     * Generates scaffolding for error handling intents.
     */
    private fun generateErrorIntentPattern(
        builder: CodeBlock.Builder,
        intentClassName: String,
        stateType: TypeName,
        sideEffectType: TypeName
    ) {
        builder.addStatement("// is $intentClassName.ClearError -> {")
        builder.addStatement("//     val newState = currentState.copy(error = null)")
        builder.addStatement("//     ReducerResult(newState)")
        builder.addStatement("// }")
        builder.addStatement("")
    }

    /**
     * Generates scaffolding for selection-type intents.
     */
    private fun generateSelectionIntentPattern(
        builder: CodeBlock.Builder,
        intentClassName: String,
        stateType: TypeName,
        sideEffectType: TypeName
    ) {
        builder.addStatement("// is $intentClassName.Select -> {")
        builder.addStatement("//     // TODO: Implement selection logic")
        builder.addStatement(
            "//     val sideEffects = listOf(${
                intentClassName.replace(
                    "Intent",
                    "SideEffect"
                )
            }.NavigateToDetail(selectedId))"
        )
        builder.addStatement("//     ReducerResult(currentState, sideEffects)")
        builder.addStatement("// }")
        builder.addStatement("")
    }

    /**
     * Generates generic scaffolding when intent structure is unknown.
     */
    private fun generateGenericScaffolding(
        builder: CodeBlock.Builder,
        metadata: MviMetadata,
        stateType: TypeName,
        sideEffectType: TypeName
    ) {
        builder.addStatement("// TODO: Implement your intent handling logic")
        builder.addStatement("// Example patterns:")
        builder.addStatement("//")
        builder.addStatement("// Loading pattern:")
        builder.addStatement("// is YourIntent.Load -> {")
        builder.addStatement("//     val newState = currentState.copy(isLoading = true, error = null)")
        builder.addStatement("//     ReducerResult(newState)")
        builder.addStatement("// }")
        builder.addStatement("//")
        builder.addStatement("// Success pattern:")
        builder.addStatement("// is YourIntent.LoadSuccess -> {")
        builder.addStatement("//     val newState = currentState.copy(")
        builder.addStatement("//         data = intent.data,")
        builder.addStatement("//         isLoading = false,")
        builder.addStatement("//         error = null")
        builder.addStatement("//     )")
        builder.addStatement("//     ReducerResult(newState)")
        builder.addStatement("// }")
        builder.addStatement("//")
        builder.addStatement("// Error pattern:")
        builder.addStatement("// is YourIntent.LoadError -> {")
        builder.addStatement("//     val newState = currentState.copy(")
        builder.addStatement("//         isLoading = false,")
        builder.addStatement("//         error = intent.error")
        builder.addStatement("//     )")
        builder.addStatement("//     val sideEffects = listOf(YourSideEffect.ShowError(intent.error))")
        builder.addStatement("//     ReducerResult(newState, sideEffects)")
        builder.addStatement("// }")
        builder.addStatement("")
        builder.addStatement("else -> ReducerResult(currentState)")
    }

    /**
     * Adds reducer-specific imports to the file spec.
     */
    private fun FileSpec.Builder.addReducerImports(metadata: MviMetadata): FileSpec.Builder {
        return apply {
            addImport("io.flowkit.core", "MviReducer", "ReducerResult")

            // Add DI imports based on framework
            when (metadata.diConfig.framework) {
                DependencyInjection.KOIN -> {
                    addImport("org.koin.core", "Koin")
                    addImport("org.koin.core.component", "get")
                }

                DependencyInjection.HILT -> {
                    addImport("javax.inject", "Inject")
                }

                else -> { /* No additional imports needed */
                }
            }
        }
    }

    /**
     * Writes the generated file to the appropriate output directory.
     */
    private fun writeFile(fileSpec: FileSpec, metadata: MviMetadata) {
        try {
            // Create a new file using KSP CodeGenerator
            val file = codeGenerator.createNewFile(
                dependencies = Dependencies(false),
                packageName = metadata.generationConfig.outputPackage,
                fileName = metadata.generationConfig.reducerClassName
            )

            // Write the FileSpec content to the file
            file.bufferedWriter().use { writer ->
                fileSpec.writeTo(writer)
            }

            logger.info("📝 FlowKit: Generated reducer: ${metadata.generationConfig.reducerClassName}.kt")

        } catch (exception: Exception) {
            logger.error("❌ FlowKit: Failed to write reducer file: ${exception.message}")
            throw exception
        }
    }
}