// flowkit-codegen/src/jvmMain/kotlin/generators/MviTestGenerator.kt
// Generates comprehensive test suites for MVI components

package io.flowkit.codegen.generators

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.squareup.kotlinpoet.BOOLEAN
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.DOUBLE
import com.squareup.kotlinpoet.FLOAT
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.INT
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.LONG
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.STRING
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.UNIT
import io.flowkit.codegen.models.MviMetadata
import io.flowkit.codegen.models.PropertyInfo

/**
 * Generates comprehensive test suites for MVI components.
 *
 * This generator creates production-ready tests that cover:
 * - Unit tests for reducers (pure function testing)
 * - Integration tests for containers (state management testing)
 * - Property-based tests for state transitions
 * - Mock setups and test utilities
 * - Cross-platform test compatibility
 *
 * The generated tests follow testing best practices and provide excellent
 * coverage for MVI patterns while being easy to understand and maintain.
 */
class MviTestGenerator(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger
) {

    /**
     * Generates complete test suites for the MVI components.
     */
    fun generate(metadata: MviMetadata) {
        logger.info("🧪 FlowKit: Generating test suites for ${metadata.stateInfo.simpleName}")

        try {
            // Generate reducer tests (pure function tests)
            generateReducerTests(metadata)

            // Generate container tests (integration tests)
            generateContainerTests(metadata)

            // Generate test utilities and mocks
            generateTestUtilities(metadata)

            logger.info("✅ FlowKit: Successfully generated test suites")

        } catch (exception: Exception) {
            logger.error("❌ FlowKit: Failed to generate tests: ${exception.message}")
            throw exception
        }
    }

    /**
     * Generates unit tests for the reducer implementation.
     */
    private fun generateReducerTests(metadata: MviMetadata) {
        val testClass = buildReducerTestClass(metadata)

        val fileSpec = FileSpec.builder(
            packageName = metadata.generationConfig.outputPackage,
            fileName = "${metadata.generationConfig.reducerClassName}Test"
        )
            .addFileComment("Generated by FlowKit CodeGen - Reducer Unit Tests")
            .addFileComment("These tests verify the pure function behavior of the reducer")
            .addTestImports()
            .addType(testClass)
            .build()

        writeTestFile(fileSpec, "${metadata.generationConfig.reducerClassName}Test")
    }

    /**
     * Builds the reducer test class with comprehensive test coverage.
     */
    private fun buildReducerTestClass(metadata: MviMetadata): TypeSpec {
        val stateType = ClassName(metadata.stateInfo.packageName, metadata.stateInfo.simpleName)
        val intentType = metadata.intentInfo?.let {
            ClassName(it.packageName, it.simpleName)
        } ?: UNIT
        val sideEffectType = metadata.sideEffectInfo?.let {
            ClassName(it.packageName, it.simpleName)
        } ?: UNIT

        return TypeSpec.classBuilder("${metadata.generationConfig.reducerClassName}Test")
            .addKdoc(buildReducerTestKDoc(metadata))
            .addProperties(buildReducerTestProperties(metadata))
            .addFunctions(
                buildReducerTestFunctions(
                    metadata,
                    stateType,
                    intentType,
                    sideEffectType
                )
            )
            .build()
    }

    /**
     * Builds KDoc for the reducer test class.
     */
    private fun buildReducerTestKDoc(metadata: MviMetadata): CodeBlock {
        return CodeBlock.builder()
            .add("Unit tests for [${metadata.generationConfig.reducerClassName}].\n")
            .add("\n")
            .add("These tests verify that the reducer correctly implements MVI principles:\n")
            .add("- Pure function behavior (same input -> same output)\n")
            .add("- Immutable state handling\n")
            .add("- Correct side effect emission\n")
            .add("- Error handling and edge cases\n")
            .add("\n")
            .add("**Test Structure:**\n")
            .add("- Setup: Create initial state and dependencies\n")
            .add("- Action: Call reducer with intent\n")
            .add("- Verify: Assert new state and side effects\n")
            .build()
    }

    /**
     * Builds properties for the reducer test class.
     */
    private fun buildReducerTestProperties(metadata: MviMetadata): List<PropertySpec> {
        return listOf(
            // Mock repository
            PropertySpec.builder(
                "mockRepository",
                guessRepositoryType(metadata),
                KModifier.PRIVATE
            )
                .delegate("mockk<${guessRepositoryType(metadata).simpleName}>()")
                .addKdoc("Mock repository for testing reducer behavior")
                .build(),

            // Reducer under test
            PropertySpec.builder(
                "reducer",
                ClassName(
                    metadata.generationConfig.outputPackage,
                    metadata.generationConfig.reducerClassName
                ),
                KModifier.PRIVATE
            )
                .delegate("lazy { ${metadata.generationConfig.reducerClassName}(mockRepository) }")
                .addKdoc("Reducer instance under test")
                .build(),

            // Initial state
            PropertySpec.builder(
                "initialState",
                ClassName(metadata.stateInfo.packageName, metadata.stateInfo.simpleName),
                KModifier.PRIVATE
            )
                .initializer("${metadata.stateInfo.simpleName}()")
                .addKdoc("Initial state for testing")
                .build()
        )
    }

    /**
     * Builds test functions for the reducer.
     */
    private fun buildReducerTestFunctions(
        metadata: MviMetadata,
        stateType: TypeName,
        intentType: TypeName,
        sideEffectType: TypeName
    ): List<FunSpec> {
        return listOf(
            buildSetupFunction(),
            buildInitialStateTest(metadata),
            buildPureFunctionTest(metadata),
            buildStateImmutabilityTest(metadata),
            buildSideEffectTest(metadata),
            buildErrorHandlingTest(metadata),
            buildPropertyBasedTest(metadata)
        )
    }

    /**
     * Builds the test setup function.
     */
    private fun buildSetupFunction(): FunSpec {
        return FunSpec.builder("setup")
            .addAnnotation(ClassName("org.junit.jupiter.api", "BeforeEach"))
            .addKdoc("Sets up test dependencies before each test.")
            .addCode(
                CodeBlock.builder()
                    .addStatement("// Clear all mocks before each test")
                    .addStatement("clearAllMocks()")
                    .addStatement("")
                    .addStatement("// Setup default mock behaviors")
                    .addStatement("// every { mockRepository.someMethod() } returns mockData")
                    .build()
            )
            .build()
    }

    /**
     * Builds test for initial state handling.
     */
    private fun buildInitialStateTest(metadata: MviMetadata): FunSpec {
        return FunSpec.builder("should_have_correct_initial_state")
            .addAnnotation(ClassName("org.junit.jupiter.api", "Test"))
            .addKdoc("Verifies that the initial state is correctly structured.")
            .addCode(
                CodeBlock.builder()
                    .addStatement("// Given: Initial state")
                    .addStatement("val state = initialState")
                    .addStatement("")
                    .addStatement("// Then: Verify initial state properties")
                    .addStatement("// TODO: Add assertions for your initial state")
                    .addStatement("// assertThat(state.isLoading).isFalse()")
                    .addStatement("// assertThat(state.error).isNull()")
                    .addStatement("// assertThat(state.data).isEmpty()")
                    .build()
            )
            .build()
    }

    /**
     * Builds test for pure function behavior.
     */
    private fun buildPureFunctionTest(metadata: MviMetadata): FunSpec {
        return FunSpec.builder("should_be_pure_function")
            .addAnnotation(ClassName("org.junit.jupiter.api", "Test"))
            .addKdoc("Verifies that the reducer behaves as a pure function.")
            .addCode(
                CodeBlock.builder()
                    .addStatement("runTest {")
                    .indent()
                    .addStatement("// Given: Same state and intent")
                    .addStatement("val state = initialState")
                    .addStatement("// val intent = YourIntent.SomeAction")
                    .addStatement("")
                    .addStatement("// When: Calling reducer multiple times")
                    .addStatement("// val result1 = reducer.reduce(state, intent)")
                    .addStatement("// val result2 = reducer.reduce(state, intent)")
                    .addStatement("")
                    .addStatement("// Then: Results should be identical")
                    .addStatement("// assertThat(result1).isEqualTo(result2)")
                    .addStatement("// assertThat(result1.newState).isEqualTo(result2.newState)")
                    .addStatement("// assertThat(result1.sideEffects).isEqualTo(result2.sideEffects)")
                    .unindent()
                    .addStatement("}")
                    .build()
            )
            .build()
    }

    /**
     * Builds test for state immutability.
     */
    private fun buildStateImmutabilityTest(metadata: MviMetadata): FunSpec {
        return FunSpec.builder("should_not_mutate_current_state")
            .addAnnotation(ClassName("org.junit.jupiter.api", "Test"))
            .addKdoc("Verifies that the reducer never mutates the current state.")
            .addCode(
                CodeBlock.builder()
                    .addStatement("runTest {")
                    .indent()
                    .addStatement("// Given: Initial state")
                    .addStatement("val originalState = initialState")
                    .addStatement("// val intent = YourIntent.ModifyState")
                    .addStatement("")
                    .addStatement("// When: Processing intent")
                    .addStatement("// val result = reducer.reduce(originalState, intent)")
                    .addStatement("")
                    .addStatement("// Then: Original state should be unchanged")
                    .addStatement("// assertThat(originalState).isEqualTo(initialState)")
                    .addStatement("// assertThat(result.newState).isNotSameInstanceAs(originalState)")
                    .unindent()
                    .addStatement("}")
                    .build()
            )
            .build()
    }

    /**
     * Builds test for side effect emission.
     */
    private fun buildSideEffectTest(metadata: MviMetadata): FunSpec {
        return FunSpec.builder("should_emit_correct_side_effects")
            .addAnnotation(ClassName("org.junit.jupiter.api", "Test"))
            .addKdoc("Verifies that the reducer emits appropriate side effects.")
            .addCode(
                CodeBlock.builder()
                    .addStatement("runTest {")
                    .indent()
                    .addStatement("// Given: State that should trigger side effects")
                    .addStatement("val state = initialState")
                    .addStatement("// val intent = YourIntent.TriggerSideEffect")
                    .addStatement("")
                    .addStatement("// When: Processing intent")
                    .addStatement("// val result = reducer.reduce(state, intent)")
                    .addStatement("")
                    .addStatement("// Then: Correct side effects should be emitted")
                    .addStatement("// assertThat(result.sideEffects).hasSize(1)")
                    .addStatement("// assertThat(result.sideEffects[0]).isInstanceOf<YourSideEffect.ExpectedEffect>()")
                    .unindent()
                    .addStatement("}")
                    .build()
            )
            .build()
    }

    /**
     * Builds test for error handling.
     */
    private fun buildErrorHandlingTest(metadata: MviMetadata): FunSpec {
        return FunSpec.builder("should_handle_errors_gracefully")
            .addAnnotation(ClassName("org.junit.jupiter.api", "Test"))
            .addKdoc("Verifies that the reducer handles error cases gracefully.")
            .addCode(
                CodeBlock.builder()
                    .addStatement("runTest {")
                    .indent()
                    .addStatement("// Given: Error state or problematic intent")
                    .addStatement("val state = initialState")
                    .addStatement("// val errorIntent = YourIntent.ErrorCase")
                    .addStatement("")
                    .addStatement("// When: Processing error intent")
                    .addStatement("// val result = reducer.reduce(state, errorIntent)")
                    .addStatement("")
                    .addStatement("// Then: Error should be handled gracefully")
                    .addStatement("// assertThat(result.newState.error).isNotNull()")
                    .addStatement("// assertThat(result.newState.isLoading).isFalse()")
                    .unindent()
                    .addStatement("}")
                    .build()
            )
            .build()
    }

    /**
     * Builds property-based test for state transitions.
     */
    private fun buildPropertyBasedTest(metadata: MviMetadata): FunSpec {
        return FunSpec.builder("should_maintain_state_invariants")
            .addAnnotation(ClassName("org.junit.jupiter.api", "Test"))
            .addKdoc("Property-based test to verify state invariants are maintained.")
            .addCode(
                CodeBlock.builder()
                    .addStatement("// TODO: Implement property-based tests using Kotest properties")
                    .addStatement("// checkAll<YourIntent> { intent ->")
                    .addStatement("//     runTest {")
                    .addStatement("//         val result = reducer.reduce(initialState, intent)")
                    .addStatement("//         // Verify state invariants")
                    .addStatement("//         assertThat(result.newState).satisfies {")
                    .addStatement("//             // Add your invariant checks here")
                    .addStatement("//         }")
                    .addStatement("//     }")
                    .addStatement("// }")
                    .build()
            )
            .build()
    }

    /**
     * Generates integration tests for the MVI container.
     */
    private fun generateContainerTests(metadata: MviMetadata) {
        val testClass = buildContainerTestClass(metadata)

        val fileSpec = FileSpec.builder(
            packageName = metadata.generationConfig.outputPackage,
            fileName = "${metadata.generationConfig.containerClassName}Test"
        )
            .addFileComment("Generated by FlowKit CodeGen - Container Integration Tests")
            .addFileComment("These tests verify the complete MVI flow and state management")
            .addTestImports()
            .addType(testClass)
            .build()

        writeTestFile(fileSpec, "${metadata.generationConfig.containerClassName}Test")
    }

    /**
     * Builds the container test class.
     */
    private fun buildContainerTestClass(metadata: MviMetadata): TypeSpec {
        return TypeSpec.classBuilder("${metadata.generationConfig.containerClassName}Test")
            .addKdoc(buildContainerTestKDoc(metadata))
            .addProperties(buildContainerTestProperties(metadata))
            .addFunctions(buildContainerTestFunctions(metadata))
            .build()
    }

    /**
     * Builds KDoc for the container test class.
     */
    private fun buildContainerTestKDoc(metadata: MviMetadata): CodeBlock {
        return CodeBlock.builder()
            .add("Integration tests for [${metadata.generationConfig.containerClassName}].\n")
            .add("\n")
            .add("These tests verify the complete MVI flow:\n")
            .add("- Intent processing and queueing\n")
            .add("- State updates and emission\n")
            .add("- Side effect handling\n")
            .add("- Thread safety and concurrency\n")
            .add("- Container lifecycle management\n")
            .build()
    }

    /**
     * Builds properties for the container test class.
     */
    private fun buildContainerTestProperties(metadata: MviMetadata): List<PropertySpec> {
        return listOf(
            // Test scope
            PropertySpec.builder(
                "testScope",
                ClassName("kotlinx.coroutines.test", "TestScope"),
                KModifier.PRIVATE
            )
                .delegate("TestScope()")
                .build(),

            // Mock repository
            PropertySpec.builder(
                "mockRepository",
                guessRepositoryType(metadata),
                KModifier.PRIVATE
            )
                .delegate("mockk<${guessRepositoryType(metadata).simpleName}>()")
                .build(),

            // Container under test
            PropertySpec.builder(
                "container",
                ClassName(
                    metadata.generationConfig.outputPackage,
                    metadata.generationConfig.containerClassName
                ),
                KModifier.PRIVATE
            )
                .delegate("lazy { ${metadata.generationConfig.containerClassName}(testScope, mockRepository) }")
                .build()
        )
    }

    /**
     * Builds test functions for the container.
     */
    private fun buildContainerTestFunctions(metadata: MviMetadata): List<FunSpec> {
        return listOf(
            buildContainerSetupFunction(),
            buildInitialStateContainerTest(metadata),
            buildIntentProcessingTest(metadata),
            buildStateFlowTest(metadata),
            buildSideEffectFlowTest(metadata),
            buildConcurrencyTest(metadata),
            buildCleanupTest(metadata)
        )
    }

    /**
     * Builds setup function for container tests.
     */
    private fun buildContainerSetupFunction(): FunSpec {
        return FunSpec.builder("setup")
            .addAnnotation(ClassName("org.junit.jupiter.api", "BeforeEach"))
            .addCode(
                CodeBlock.builder()
                    .addStatement("clearAllMocks()")
                    .build()
            )
            .build()
    }

    /**
     * Builds test for initial state in container.
     */
    private fun buildInitialStateContainerTest(metadata: MviMetadata): FunSpec {
        return FunSpec.builder("should_emit_initial_state")
            .addAnnotation(ClassName("org.junit.jupiter.api", "Test"))
            .addCode(
                CodeBlock.builder()
                    .addStatement("// Given: Container is created")
                    .addStatement("val container = this.container")
                    .addStatement("")
                    .addStatement("// Then: Initial state should be emitted")
                    .addStatement("val currentState = container.currentState()")
                    .addStatement("// TODO: Add assertions for initial state")
                    .addStatement("// assertThat(currentState).isEqualTo(expectedInitialState)")
                    .build()
            )
            .build()
    }

    /**
     * Builds test for intent processing.
     */
    private fun buildIntentProcessingTest(metadata: MviMetadata): FunSpec {
        return FunSpec.builder("should_process_intents_sequentially")
            .addAnnotation(ClassName("org.junit.jupiter.api", "Test"))
            .addCode(
                CodeBlock.builder()
                    .addStatement("runTest {")
                    .indent()
                    .addStatement("// Given: Multiple intents")
                    .addStatement("// val intent1 = YourIntent.FirstAction")
                    .addStatement("// val intent2 = YourIntent.SecondAction")
                    .addStatement("")
                    .addStatement("// When: Processing intents")
                    .addStatement("// container.processIntent(intent1)")
                    .addStatement("// container.processIntent(intent2)")
                    .addStatement("")
                    .addStatement("// Then: Intents should be processed in order")
                    .addStatement("// advanceUntilIdle()")
                    .addStatement("// TODO: Verify final state reflects both intents")
                    .unindent()
                    .addStatement("}")
                    .build()
            )
            .build()
    }

    /**
     * Builds test for state flow behavior.
     */
    private fun buildStateFlowTest(metadata: MviMetadata): FunSpec {
        return FunSpec.builder("should_emit_state_changes")
            .addAnnotation(ClassName("org.junit.jupiter.api", "Test"))
            .addCode(
                CodeBlock.builder()
                    .addStatement("runTest {")
                    .indent()
                    .addStatement("// Given: State flow observer")
                    .addStatement("val stateValues = mutableListOf<${metadata.stateInfo.simpleName}>()")
                    .addStatement("val job = launch {")
                    .indent()
                    .addStatement("container.state.collect { stateValues.add(it) }")
                    .unindent()
                    .addStatement("}")
                    .addStatement("")
                    .addStatement("// When: Processing state-changing intent")
                    .addStatement("// container.processIntent(YourIntent.ChangeState)")
                    .addStatement("// advanceUntilIdle()")
                    .addStatement("")
                    .addStatement("// Then: State changes should be emitted")
                    .addStatement("// assertThat(stateValues).hasSize(2) // initial + changed")
                    .addStatement("")
                    .addStatement("job.cancel()")
                    .unindent()
                    .addStatement("}")
                    .build()
            )
            .build()
    }

    /**
     * Builds test for side effect flow behavior.
     */
    private fun buildSideEffectFlowTest(metadata: MviMetadata): FunSpec {
        return FunSpec.builder("should_emit_side_effects")
            .addAnnotation(ClassName("org.junit.jupiter.api", "Test"))
            .addCode(
                CodeBlock.builder()
                    .addStatement("runTest {")
                    .indent()
                    .addStatement("// Given: Side effect observer")
                    .addStatement("val sideEffects = mutableListOf<${metadata.sideEffectInfo?.simpleName ?: "Any"}>()")
                    .addStatement("val job = launch {")
                    .indent()
                    .addStatement("container.sideEffects.collect { sideEffects.add(it) }")
                    .unindent()
                    .addStatement("}")
                    .addStatement("")
                    .addStatement("// When: Processing intent that emits side effect")
                    .addStatement("// container.processIntent(YourIntent.TriggerSideEffect)")
                    .addStatement("// advanceUntilIdle()")
                    .addStatement("")
                    .addStatement("// Then: Side effect should be emitted")
                    .addStatement("// assertThat(sideEffects).hasSize(1)")
                    .addStatement("// assertThat(sideEffects[0]).isInstanceOf<YourSideEffect.Expected>()")
                    .addStatement("")
                    .addStatement("job.cancel()")
                    .unindent()
                    .addStatement("}")
                    .build()
            )
            .build()
    }

    /**
     * Builds test for concurrency and thread safety.
     */
    private fun buildConcurrencyTest(metadata: MviMetadata): FunSpec {
        return FunSpec.builder("should_handle_concurrent_intents")
            .addAnnotation(ClassName("org.junit.jupiter.api", "Test"))
            .addCode(
                CodeBlock.builder()
                    .addStatement("runTest {")
                    .indent()
                    .addStatement("// Given: Multiple concurrent intents")
                    .addStatement("val intentCount = 100")
                    .addStatement("")
                    .addStatement("// When: Processing many intents concurrently")
                    .addStatement("repeat(intentCount) { index ->")
                    .indent()
                    .addStatement("launch {")
                    .indent()
                    .addStatement("// container.processIntent(YourIntent.ConcurrentAction(index))")
                    .unindent()
                    .addStatement("}")
                    .unindent()
                    .addStatement("}")
                    .addStatement("")
                    .addStatement("// Then: All intents should be processed safely")
                    .addStatement("// advanceUntilIdle()")
                    .addStatement("// TODO: Verify final state is consistent")
                    .unindent()
                    .addStatement("}")
                    .build()
            )
            .build()
    }

    /**
     * Builds test for container cleanup.
     */
    private fun buildCleanupTest(metadata: MviMetadata): FunSpec {
        return FunSpec.builder("should_cleanup_resources_when_closed")
            .addAnnotation(ClassName("org.junit.jupiter.api", "Test"))
            .addCode(
                CodeBlock.builder()
                    .addStatement("runTest {")
                    .indent()
                    .addStatement("// Given: Container with active flows")
                    .addStatement("val container = this@${metadata.generationConfig.containerClassName}Test.container")
                    .addStatement("")
                    .addStatement("// When: Closing the container")
                    .addStatement("container.close()")
                    .addStatement("")
                    .addStatement("// Then: Resources should be cleaned up")
                    .addStatement("// TODO: Verify that flows are closed and resources released")
                    .addStatement("// This prevents memory leaks in production")
                    .unindent()
                    .addStatement("}")
                    .build()
            )
            .build()
    }

    /**
     * Generates test utilities and helper classes.
     */
    private fun generateTestUtilities(metadata: MviMetadata) {
        val utilityClass = buildTestUtilityClass(metadata)

        val fileSpec = FileSpec.builder(
            packageName = metadata.generationConfig.outputPackage,
            fileName = "${metadata.stateInfo.simpleName.replace("State", "")}TestUtils"
        )
            .addFileComment("Generated by FlowKit CodeGen - Test Utilities")
            .addFileComment("Helper functions and utilities for testing MVI components")
            .addTestImports()
            .addType(utilityClass)
            .build()

        writeTestFile(fileSpec, "${metadata.stateInfo.simpleName.replace("State", "")}TestUtils")
    }

    /**
     * Builds test utility class with helper functions.
     */
    private fun buildTestUtilityClass(metadata: MviMetadata): TypeSpec {
        return TypeSpec.objectBuilder(
            "${
                metadata.stateInfo.simpleName.replace(
                    "State",
                    ""
                )
            }TestUtils"
        )
            .addKdoc(buildTestUtilityKDoc(metadata))
            .addFunctions(buildTestUtilityFunctions(metadata))
            .build()
    }

    /**
     * Builds KDoc for test utility class.
     */
    private fun buildTestUtilityKDoc(metadata: MviMetadata): CodeBlock {
        return CodeBlock.builder()
            .add("Test utilities for ${metadata.stateInfo.simpleName} MVI components.\n")
            .add("\n")
            .add("This object provides:\n")
            .add("- Factory methods for creating test data\n")
            .add("- Assertion helpers for common test scenarios\n")
            .add("- Mock setup utilities\n")
            .add("- Test state builders\n")
            .build()
    }

    /**
     * Builds utility functions for testing.
     */
    private fun buildTestUtilityFunctions(metadata: MviMetadata): List<FunSpec> {
        return listOf(
            buildStateBuilderFunction(metadata),
            buildMockRepositoryFunction(metadata),
            buildAssertionHelpers(metadata),
            buildTestDataFactories(metadata)
        )
    }

    /**
     * Builds a test state builder function.
     */
    private fun buildStateBuilderFunction(metadata: MviMetadata): FunSpec {
        return FunSpec.builder("createTestState")
            .addKdoc("Creates a test state with optional parameter overrides.")
            .returns(ClassName(metadata.stateInfo.packageName, metadata.stateInfo.simpleName))
            .addParameters(buildTestStateParameters(metadata))
            .addCode(
                CodeBlock.builder()
                    .addStatement("return ${metadata.stateInfo.simpleName}(")
                    .indent()
                    .apply {
                        metadata.stateInfo.properties.forEach { property ->
                            addStatement("${property.name} = ${property.name},")
                        }
                    }
                    .unindent()
                    .addStatement(")")
                    .build()
            )
            .build()
    }

    /**
     * Builds parameters for the test state builder.
     */
    private fun buildTestStateParameters(metadata: MviMetadata): List<ParameterSpec> {
        return metadata.stateInfo.properties.map { property ->
            ParameterSpec.builder(property.name, property.type.asTypeName())
                .defaultValue(getDefaultValueForProperty(property))
                .build()
        }
    }

    /**
     * Gets appropriate default value for a property in tests.
     */
    private fun getDefaultValueForProperty(property: PropertyInfo): String {
        return when {
            property.defaultValue != null -> property.defaultValue
            property.type.contains("Boolean") -> "false"
            property.type.contains("String") -> "\"\""
            property.type.contains("Int") -> "0"
            property.type.contains("List") -> "emptyList()"
            property.isNullable -> "null"
            else -> "TODO(\"Provide default value for ${property.name}\")"
        }
    }

    /**
     * Builds mock repository setup function.
     */
    private fun buildMockRepositoryFunction(metadata: MviMetadata): FunSpec {
        return FunSpec.builder("setupMockRepository")
            .addKdoc("Sets up a mock repository with common test behaviors.")
            .returns(guessRepositoryType(metadata))
            .addCode(
                CodeBlock.builder()
                    .addStatement("val mockRepository = mockk<${guessRepositoryType(metadata).simpleName}>()")
                    .addStatement("")
                    .addStatement("// Setup common mock behaviors")
                    .addStatement("// every { mockRepository.getData() } returns flowOf(testData)")
                    .addStatement("// every { mockRepository.saveData(any()) } returns Unit")
                    .addStatement("")
                    .addStatement("return mockRepository")
                    .build()
            )
            .build()
    }

    /**
     * Builds assertion helper functions.
     */
    private fun buildAssertionHelpers(metadata: MviMetadata): FunSpec {
        return FunSpec.builder("assertStateEquals")
            .addKdoc("Custom assertion for state equality with detailed error messages.")
            .addParameter(
                "expected",
                ClassName(metadata.stateInfo.packageName, metadata.stateInfo.simpleName)
            )
            .addParameter(
                "actual",
                ClassName(metadata.stateInfo.packageName, metadata.stateInfo.simpleName)
            )
            .addCode(
                CodeBlock.builder()
                    .addStatement("// TODO: Implement detailed state comparison")
                    .addStatement("// This can provide better error messages than simple assertEquals")
                    .addStatement("assertThat(actual).isEqualTo(expected)")
                    .build()
            )
            .build()
    }

    /**
     * Builds test data factory functions.
     */
    private fun buildTestDataFactories(metadata: MviMetadata): FunSpec {
        return FunSpec.builder("createTestData")
            .addKdoc("Creates test data for use in tests.")
            .addCode(
                CodeBlock.builder()
                    .addStatement("// TODO: Create factory functions for test data")
                    .addStatement("// Example:")
                    .addStatement("// fun createTestUser() = User(id = \"test\", name = \"Test User\")")
                    .addStatement("// fun createTestUsers(count: Int) = (1..count).map { createTestUser() }")
                    .build()
            )
            .build()
    }

    /**
     * Guesses the repository type based on naming conventions.
     */
    private fun guessRepositoryType(metadata: MviMetadata): ClassName {
        val stateClassName = metadata.stateInfo.simpleName
        val repositoryName = stateClassName
            .replace("State", "Repository")
            .replace("Screen", "")

        return ClassName(metadata.stateInfo.packageName, repositoryName)
    }

    /**
     * Extension function to convert string types to TypeName.
     */
    private fun String.asTypeName(): TypeName {
        return when (this) {
            "String" -> STRING
            "Int" -> INT
            "Boolean" -> BOOLEAN
            "Long" -> LONG
            "Float" -> FLOAT
            "Double" -> DOUBLE
            else -> ClassName.bestGuess(this)
        }
    }

    /**
     * Adds test-specific imports to the file spec.
     */
    private fun FileSpec.Builder.addTestImports(): FileSpec.Builder {
        return apply {
            // JUnit 5 imports
            addImport("org.junit.jupiter.api", "Test", "BeforeEach")

            // Kotlin test imports
            addImport("kotlin.test", "assertEquals", "assertNotNull", "assertTrue", "assertFalse")

            // Coroutine test imports
            addImport("kotlinx.coroutines.test", "runTest", "TestScope", "advanceUntilIdle")
            addImport("kotlinx.coroutines", "launch")

            // MockK imports
            addImport("io.mockk", "mockk", "every", "clearAllMocks", "verify")

            // AssertJ imports (if available)
            addImport("org.assertj.core.api.Assertions", "assertThat")

            // Turbine for testing flows
            addImport("app.cash.turbine", "test")
        }
    }

    /**
     * Writes test files to the test source directory.
     */
    private fun writeTestFile(fileSpec: FileSpec, fileName: String) {
        try {
            // Create a new file using KSP CodeGenerator
            val file = codeGenerator.createNewFile(
                dependencies = Dependencies(false),
                packageName = fileSpec.packageName,
                fileName = fileName
            )

            // Write the FileSpec content to the file
            file.bufferedWriter().use { writer ->
                fileSpec.writeTo(writer)
            }

            logger.info("📝 FlowKit: Generated test file: $fileName.kt")

        } catch (exception: Exception) {
            logger.error("❌ FlowKit: Failed to write test file: ${exception.message}")
            throw exception
        }
    }
}