// flowkit-codegen/src/jvmMain/kotlin/generators/MviViewModelGenerator.kt
// Generates platform-specific ViewModel wrappers for MVI containers

package io.flowkit.codegen.generators

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.LambdaTypeName
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.UNIT
import io.flowkit.codegen.annotations.DependencyInjection
import io.flowkit.codegen.annotations.TargetPlatform
import io.flowkit.codegen.models.MviMetadata

/**
 * Generates platform-specific ViewModel wrappers for MVI containers.
 *
 * ViewModels provide the bridge between the platform's UI layer and our MVI container.
 * This generator creates different ViewModel implementations based on the target platform:
 * - Android: Extends androidx.lifecycle.ViewModel with proper lifecycle management
 * - iOS: Creates a view model class that follows iOS patterns and Swift interop
 * - Common: Creates a basic view model wrapper for other platforms
 */
class MviViewModelGenerator(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger
) {

    /**
     * Generates ViewModel wrappers for all target platforms.
     */
    fun generate(metadata: MviMetadata) {
        val viewModelClassName = metadata.generationConfig.viewModelClassName
        logger.info("🎮 FlowKit: Generating ViewModels: $viewModelClassName")

        try {
            // Generate platform-specific ViewModels based on targets
            metadata.platformConfig.targets.forEach { platform ->
                when (platform) {
                    TargetPlatform.ANDROID -> generateAndroidViewModel(metadata)
                    TargetPlatform.IOS -> generateIosViewModel(metadata)
                    TargetPlatform.ALL -> {
                        generateAndroidViewModel(metadata)
                        generateIosViewModel(metadata)
                        generateCommonViewModel(metadata)
                    }

                    else -> generateCommonViewModel(metadata)
                }
            }

            logger.info("✅ FlowKit: Successfully generated ViewModels for ${metadata.stateInfo.simpleName}")

        } catch (exception: Exception) {
            logger.error("❌ FlowKit: Failed to generate ViewModels: ${exception.message}")
            throw exception
        }
    }

    /**
     * Generates Android ViewModel with androidx.lifecycle.ViewModel integration.
     */
    private fun generateAndroidViewModel(metadata: MviMetadata) {
        val viewModelClass = buildAndroidViewModelClass(metadata)

        val fileSpec = FileSpec.builder(
            packageName = metadata.generationConfig.outputPackage,
            fileName = metadata.generationConfig.viewModelClassName
        )
            .addFileComment("Generated by FlowKit CodeGen - Android ViewModel")
            .addFileComment("Integrates with Android lifecycle and dependency injection")
            .addAndroidImports(metadata)
            .addType(viewModelClass)
            .build()

        writeFile(fileSpec, metadata)
    }

    /**
     * Builds the Android ViewModel class with proper lifecycle integration.
     */
    private fun buildAndroidViewModelClass(metadata: MviMetadata): TypeSpec {
        val stateType = ClassName(metadata.stateInfo.packageName, metadata.stateInfo.simpleName)
        val intentType = metadata.intentInfo?.let {
            ClassName(it.packageName, it.simpleName)
        } ?: UNIT
        val sideEffectType = metadata.sideEffectInfo?.let {
            ClassName(it.packageName, it.simpleName)
        } ?: UNIT

        return TypeSpec.classBuilder(metadata.generationConfig.viewModelClassName)
            .superclass(ClassName("androidx.lifecycle", "ViewModel"))
            .addKdoc(buildAndroidViewModelKDoc(metadata))
            .primaryConstructor(buildAndroidViewModelConstructor(metadata))
            .addProperties(buildAndroidViewModelProperties(metadata, stateType, sideEffectType))
            .addFunctions(buildAndroidViewModelFunctions(metadata, intentType, stateType))
            .apply {
                // Add dependency injection annotations
                when (metadata.diConfig.framework) {
                    DependencyInjection.HILT -> {
                        addAnnotation(ClassName("dagger.hilt.android.lifecycle", "HiltViewModel"))
                    }

                    DependencyInjection.KOIN -> {
                        // Koin doesn't require class-level annotations for ViewModels
                    }

                    else -> { /* Manual DI */
                    }
                }
            }
            .build()
    }

    /**
     * Builds KDoc for the Android ViewModel.
     */
    private fun buildAndroidViewModelKDoc(metadata: MviMetadata): CodeBlock {
        return CodeBlock.builder()
            .add("Android ViewModel for [${metadata.stateInfo.simpleName}] with lifecycle integration.\n")
            .add("\n")
            .add("This ViewModel:\n")
            .add("- Automatically manages the MVI container lifecycle\n")
            .add("- Provides Android-specific state and side effect handling\n")
            .add("- Integrates with ${metadata.diConfig.framework} dependency injection\n")
            .add("- Follows Android Architecture Components patterns\n")
            .add("\n")
            .add("**Usage in Composables:**\n")
            .add("```kotlin\n")
            .add("@Composable\n")
            .add("fun ${metadata.stateInfo.simpleName.replace("State", "Screen")}() {\n")
            .add("    val viewModel: ${metadata.generationConfig.viewModelClassName} = hiltViewModel()\n")
            .add("    val state by viewModel.state.collectAsState()\n")
            .add("    \n")
            .add("    LaunchedEffect(Unit) {\n")
            .add("        viewModel.sideEffects.collect { sideEffect ->\n")
            .add("            // Handle side effects\n")
            .add("        }\n")
            .add("    }\n")
            .add("}\n")
            .add("```\n")
            .build()
    }

    /**
     * Builds the Android ViewModel constructor with DI support.
     */
    private fun buildAndroidViewModelConstructor(metadata: MviMetadata): FunSpec {
        val constructor = FunSpec.constructorBuilder()

        when (metadata.diConfig.framework) {
            DependencyInjection.HILT -> {
                constructor.addAnnotation(ClassName("javax.inject", "Inject"))
                val repositoryType = guessRepositoryType(metadata)
                constructor.addParameter("repository", repositoryType)
            }

            DependencyInjection.KOIN -> {
                // Koin injects through property delegation in ViewModel
            }

            else -> {
                val repositoryType = guessRepositoryType(metadata)
                constructor.addParameter("repository", repositoryType)
            }
        }

        return constructor.build()
    }

    /**
     * Builds properties for the Android ViewModel.
     */
    private fun buildAndroidViewModelProperties(
        metadata: MviMetadata,
        stateType: TypeName,
        sideEffectType: TypeName
    ): List<PropertySpec> {
        val properties = mutableListOf<PropertySpec>()

        // MVI Container instance
        properties.add(
            PropertySpec.builder(
                "container",
                ClassName(
                    metadata.generationConfig.outputPackage,
                    metadata.generationConfig.containerClassName
                ),
                KModifier.PRIVATE
            )
                .initializer(buildContainerInitializer(metadata))
                .addKdoc("Internal MVI container that manages state and processes intents.")
                .build()
        )

        // Exposed state flow
        properties.add(
            PropertySpec.builder(
                "state",
                ClassName("kotlinx.coroutines.flow", "StateFlow").parameterizedBy(stateType)
            )
                .initializer("container.state")
                .addKdoc("Reactive state flow for observing state changes in Compose.")
                .build()
        )

        // Exposed side effects flow
        properties.add(
            PropertySpec.builder(
                "sideEffects",
                ClassName("kotlinx.coroutines.flow", "Flow").parameterizedBy(sideEffectType)
            )
                .initializer("container.sideEffects")
                .addKdoc("One-time side effects flow for handling navigation, dialogs, etc.")
                .build()
        )

        return properties
    }

    /**
     * Builds the container initializer based on DI framework.
     */
    private fun buildContainerInitializer(metadata: MviMetadata): String {
        return when (metadata.diConfig.framework) {
            DependencyInjection.HILT -> {
                "${metadata.generationConfig.containerClassName}(viewModelScope, repository)"
            }

            DependencyInjection.KOIN -> {
                "${metadata.generationConfig.containerClassName}(viewModelScope, get())"
            }

            else -> {
                "${metadata.generationConfig.containerClassName}(viewModelScope, repository)"
            }
        }
    }

    /**
     * Builds functions for the Android ViewModel.
     */
    private fun buildAndroidViewModelFunctions(
        metadata: MviMetadata,
        intentType: TypeName,
        stateType: TypeName
    ): List<FunSpec> {
        return listOf(
            // Process intent function
            FunSpec.builder("processIntent")
                .addParameter("intent", intentType)
                .addKdoc(
                    """
                    Processes an intent asynchronously.
                    
                    This function is safe to call from Compose and other UI code.
                    The intent will be processed on the ViewModel's coroutine scope.
                    
                    @param intent The intent to process
                """.trimIndent()
                )
                .addCode(
                    CodeBlock.builder()
                        .addStatement("viewModelScope.launch {")
                        .indent()
                        .addStatement("container.processIntent(intent)")
                        .unindent()
                        .addStatement("}")
                        .build()
                )
                .build(),

            // Current state function
            FunSpec.builder("currentState")
                .returns(stateType)
                .addKdoc("Returns the current state value synchronously.")
                .addStatement("return container.currentState()")
                .build(),

            // OnCleared override for cleanup
            FunSpec.builder("onCleared")
                .addModifiers(KModifier.OVERRIDE)
                .addKdoc("Called when the ViewModel is destroyed. Performs cleanup.")
                .addCode(
                    CodeBlock.builder()
                        .addStatement("super.onCleared()")
                        .addStatement("container.close()")
                        .build()
                )
                .build()
        )
    }

    /**
     * Generates iOS ViewModel with Swift interoperability optimizations.
     */
    private fun generateIosViewModel(metadata: MviMetadata) {
        val viewModelClass = buildIosViewModelClass(metadata)

        val fileSpec = FileSpec.builder(
            packageName = metadata.generationConfig.outputPackage,
            fileName = "${metadata.generationConfig.viewModelClassName}Ios"
        )
            .addFileComment("Generated by FlowKit CodeGen - iOS ViewModel")
            .addFileComment("Optimized for Swift interoperability and iOS patterns")
            .addIosImports()
            .addType(viewModelClass)
            .build()

        writeFile(fileSpec, metadata, "Ios")
    }

    /**
     * Builds the iOS ViewModel class with Swift interop optimizations.
     */
    private fun buildIosViewModelClass(metadata: MviMetadata): TypeSpec {
        val stateType = ClassName(metadata.stateInfo.packageName, metadata.stateInfo.simpleName)
        val intentType = metadata.intentInfo?.let {
            ClassName(it.packageName, it.simpleName)
        } ?: UNIT
        val sideEffectType = metadata.sideEffectInfo?.let {
            ClassName(it.packageName, it.simpleName)
        } ?: UNIT

        return TypeSpec.classBuilder("${metadata.generationConfig.viewModelClassName}Ios")
            .addKdoc(buildIosViewModelKDoc(metadata))
            .primaryConstructor(buildIosViewModelConstructor(metadata))
            .addProperties(buildIosViewModelProperties(metadata, stateType, sideEffectType))
            .addFunctions(buildIosViewModelFunctions(metadata, intentType, stateType))
            .build()
    }

    /**
     * Builds KDoc for the iOS ViewModel.
     */
    private fun buildIosViewModelKDoc(metadata: MviMetadata): CodeBlock {
        return CodeBlock.builder()
            .add("iOS ViewModel for [${metadata.stateInfo.simpleName}] with Swift interoperability.\n")
            .add("\n")
            .add("This ViewModel is optimized for iOS and Swift usage:\n")
            .add("- Memory-efficient state management\n")
            .add("- Swift-friendly API design\n")
            .add("- iOS lifecycle compatibility\n")
            .add("- Proper cleanup and resource management\n")
            .add("\n")
            .add("**Usage from Swift:**\n")
            .add("```swift\n")
            .add(
                "class ${
                    metadata.stateInfo.simpleName.replace(
                        "State",
                        "View"
                    )
                }Controller: UIViewController {\n"
            )
            .add("    private let viewModel = ${metadata.generationConfig.viewModelClassName}Ios(...)\n")
            .add("    \n")
            .add("    override func viewDidLoad() {\n")
            .add("        super.viewDidLoad()\n")
            .add("        observeState()\n")
            .add("        observeSideEffects()\n")
            .add("    }\n")
            .add("}\n")
            .add("```\n")
            .build()
    }

    /**
     * Builds the iOS ViewModel constructor.
     */
    private fun buildIosViewModelConstructor(metadata: MviMetadata): FunSpec {
        val constructor = FunSpec.constructorBuilder()
            .addParameter("scope", ClassName("kotlinx.coroutines", "CoroutineScope"))

        when (metadata.diConfig.framework) {
            DependencyInjection.KOIN -> {
                constructor.addParameter("koin", ClassName("org.koin.core", "Koin"))
            }

            else -> {
                val repositoryType = guessRepositoryType(metadata)
                constructor.addParameter("repository", repositoryType)
            }
        }

        return constructor.build()
    }

    /**
     * Builds properties for the iOS ViewModel.
     */
    private fun buildIosViewModelProperties(
        metadata: MviMetadata,
        stateType: TypeName,
        sideEffectType: TypeName
    ): List<PropertySpec> {
        return listOf(
            // MVI Container instance
            PropertySpec.builder(
                "container",
                ClassName(
                    metadata.generationConfig.outputPackage,
                    metadata.generationConfig.containerClassName
                ),
                KModifier.PRIVATE
            )
                .initializer(buildIosContainerInitializer(metadata))
                .addKdoc("Internal MVI container optimized for iOS memory management.")
                .build(),

            // State flow with iOS optimizations
            PropertySpec.builder(
                "state",
                ClassName("kotlinx.coroutines.flow", "StateFlow").parameterizedBy(stateType)
            )
                .initializer("container.state")
                .addKdoc("State flow optimized for Swift interoperability.")
                .build(),

            // Side effects flow with iOS optimizations
            PropertySpec.builder(
                "sideEffects",
                ClassName("kotlinx.coroutines.flow", "Flow").parameterizedBy(sideEffectType)
            )
                .initializer("container.sideEffects")
                .addKdoc("Side effects flow with iOS-friendly emission patterns.")
                .build()
        )
    }

    /**
     * Builds the iOS container initializer.
     */
    private fun buildIosContainerInitializer(metadata: MviMetadata): String {
        return when (metadata.diConfig.framework) {
            DependencyInjection.KOIN -> {
                "${metadata.generationConfig.containerClassName}(scope, koin.get())"
            }

            else -> {
                "${metadata.generationConfig.containerClassName}(scope, repository)"
            }
        }
    }

    /**
     * Builds functions for the iOS ViewModel.
     */
    private fun buildIosViewModelFunctions(
        metadata: MviMetadata,
        intentType: TypeName,
        stateType: TypeName
    ): List<FunSpec> {
        return listOf(
            // Process intent function with iOS-friendly signature
            FunSpec.builder("processIntent")
                .addParameter("intent", intentType)
                .addKdoc(
                    """
                    Processes an intent asynchronously with iOS-optimized handling.
                    
                    This function is safe to call from Swift and properly handles
                    iOS memory management and threading concerns.
                    
                    @param intent The intent to process
                """.trimIndent()
                )
                .addCode(
                    CodeBlock.builder()
                        .addStatement("// Process intent with iOS-specific error handling")
                        .addStatement("kotlinx.coroutines.runBlocking {")
                        .indent()
                        .addStatement("container.processIntent(intent)")
                        .unindent()
                        .addStatement("}")
                        .build()
                )
                .build(),

            // Current state function
            FunSpec.builder("currentState")
                .returns(stateType)
                .addKdoc("Returns the current state value - Swift-friendly synchronous access.")
                .addStatement("return container.currentState()")
                .build(),

            // iOS-specific state observation helper
            FunSpec.builder("observeState")
                .addParameter(
                    "callback",
                    LambdaTypeName.get(parameters = arrayOf(stateType), returnType = UNIT)
                )
                .addKdoc(
                    """
                    Helper function for observing state changes from Swift.
                    
                    This provides a Swift-friendly way to observe state changes
                    without dealing with Kotlin Flow directly.
                    
                    @param callback Function called when state changes
                """.trimIndent()
                )
                .addCode(
                    CodeBlock.builder()
                        .addStatement("// Launch collection on appropriate scope for iOS")
                        .addStatement("kotlinx.coroutines.launch {")
                        .indent()
                        .addStatement("state.collect { newState ->")
                        .indent()
                        .addStatement("callback(newState)")
                        .unindent()
                        .addStatement("}")
                        .unindent()
                        .addStatement("}")
                        .build()
                )
                .build(),

            // iOS-specific side effects observation helper
            FunSpec.builder("observeSideEffects")
                .addParameter(
                    "callback", LambdaTypeName.get(
                        parameters = arrayOf(metadata.sideEffectInfo?.let {
                            ClassName(it.packageName, it.simpleName)
                        } ?: UNIT),
                        returnType = UNIT
                    ))
                .addKdoc(
                    """
                    Helper function for observing side effects from Swift.
                    
                    @param callback Function called when side effects are emitted
                """.trimIndent()
                )
                .addCode(
                    CodeBlock.builder()
                        .addStatement("kotlinx.coroutines.launch {")
                        .indent()
                        .addStatement("sideEffects.collect { sideEffect ->")
                        .indent()
                        .addStatement("callback(sideEffect)")
                        .unindent()
                        .addStatement("}")
                        .unindent()
                        .addStatement("}")
                        .build()
                )
                .build(),

            // iOS cleanup function
            FunSpec.builder("cleanup")
                .addKdoc("Performs iOS-specific cleanup. Call when the view is deallocated.")
                .addCode(
                    CodeBlock.builder()
                        .addStatement("container.close()")
                        .build()
                )
                .build()
        )
    }

    /**
     * Generates a common ViewModel for other platforms.
     */
    private fun generateCommonViewModel(metadata: MviMetadata) {
        val viewModelClass = buildCommonViewModelClass(metadata)

        val fileSpec = FileSpec.builder(
            packageName = metadata.generationConfig.outputPackage,
            fileName = "${metadata.generationConfig.viewModelClassName}Common"
        )
            .addFileComment("Generated by FlowKit CodeGen - Common ViewModel")
            .addFileComment("Platform-agnostic ViewModel for Desktop, Web, and other platforms")
            .addCommonImports()
            .addType(viewModelClass)
            .build()

        writeFile(fileSpec, metadata, "Common")
    }

    /**
     * Builds a common ViewModel class for non-Android/iOS platforms.
     */
    private fun buildCommonViewModelClass(metadata: MviMetadata): TypeSpec {
        val stateType = ClassName(metadata.stateInfo.packageName, metadata.stateInfo.simpleName)
        val intentType = metadata.intentInfo?.let {
            ClassName(it.packageName, it.simpleName)
        } ?: UNIT
        val sideEffectType = metadata.sideEffectInfo?.let {
            ClassName(it.packageName, it.simpleName)
        } ?: UNIT

        return TypeSpec.classBuilder("${metadata.generationConfig.viewModelClassName}Common")
            .addKdoc(buildCommonViewModelKDoc(metadata))
            .primaryConstructor(buildCommonViewModelConstructor(metadata))
            .addProperties(buildCommonViewModelProperties(metadata, stateType, sideEffectType))
            .addFunctions(buildCommonViewModelFunctions(metadata, intentType, stateType))
            .build()
    }

    /**
     * Builds KDoc for the common ViewModel.
     */
    private fun buildCommonViewModelKDoc(metadata: MviMetadata): CodeBlock {
        return CodeBlock.builder()
            .add("Common ViewModel for [${metadata.stateInfo.simpleName}] across all platforms.\n")
            .add("\n")
            .add("This ViewModel provides a platform-agnostic interface to the MVI container:\n")
            .add("- Works on Desktop (Compose Desktop)\n")
            .add("- Works on Web (Compose for Web)\n")
            .add("- Works on any Kotlin platform\n")
            .add("- Provides basic lifecycle management\n")
            .build()
    }

    /**
     * Builds the common ViewModel constructor.
     */
    private fun buildCommonViewModelConstructor(metadata: MviMetadata): FunSpec {
        val constructor = FunSpec.constructorBuilder()
            .addParameter("scope", ClassName("kotlinx.coroutines", "CoroutineScope"))

        when (metadata.diConfig.framework) {
            DependencyInjection.KOIN -> {
                constructor.addParameter("koin", ClassName("org.koin.core", "Koin"))
            }

            else -> {
                val repositoryType = guessRepositoryType(metadata)
                constructor.addParameter("repository", repositoryType)
            }
        }

        return constructor.build()
    }

    /**
     * Builds properties for the common ViewModel.
     */
    private fun buildCommonViewModelProperties(
        metadata: MviMetadata,
        stateType: TypeName,
        sideEffectType: TypeName
    ): List<PropertySpec> {
        return listOf(
            // MVI Container instance
            PropertySpec.builder(
                "container",
                ClassName(
                    metadata.generationConfig.outputPackage,
                    metadata.generationConfig.containerClassName
                ),
                KModifier.PRIVATE
            )
                .initializer(buildCommonContainerInitializer(metadata))
                .build(),

            // State flow
            PropertySpec.builder(
                "state",
                ClassName("kotlinx.coroutines.flow", "StateFlow").parameterizedBy(stateType)
            )
                .initializer("container.state")
                .build(),

            // Side effects flow
            PropertySpec.builder(
                "sideEffects",
                ClassName("kotlinx.coroutines.flow", "Flow").parameterizedBy(sideEffectType)
            )
                .initializer("container.sideEffects")
                .build()
        )
    }

    /**
     * Builds the common container initializer.
     */
    private fun buildCommonContainerInitializer(metadata: MviMetadata): String {
        return when (metadata.diConfig.framework) {
            DependencyInjection.KOIN -> {
                "${metadata.generationConfig.containerClassName}(scope, koin.get())"
            }

            else -> {
                "${metadata.generationConfig.containerClassName}(scope, repository)"
            }
        }
    }

    /**
     * Builds functions for the common ViewModel.
     */
    private fun buildCommonViewModelFunctions(
        metadata: MviMetadata,
        intentType: TypeName,
        stateType: TypeName
    ): List<FunSpec> {
        return listOf(
            // Process intent function
            FunSpec.builder("processIntent")
                .addModifiers(KModifier.SUSPEND)
                .addParameter("intent", intentType)
                .addStatement("container.processIntent(intent)")
                .build(),

            // Current state function
            FunSpec.builder("currentState")
                .returns(stateType)
                .addStatement("return container.currentState()")
                .build(),

            // Close function for cleanup
            FunSpec.builder("close")
                .addStatement("container.close()")
                .build()
        )
    }

    /**
     * Guesses the repository type based on naming conventions.
     */
    private fun guessRepositoryType(metadata: MviMetadata): ClassName {
        val stateClassName = metadata.stateInfo.simpleName
        val repositoryName = stateClassName
            .replace("State", "Repository")
            .replace("Screen", "")

        return ClassName(metadata.stateInfo.packageName, repositoryName)
    }

    /**
     * Adds Android-specific imports to the file spec.
     */
    private fun FileSpec.Builder.addAndroidImports(metadata: MviMetadata): FileSpec.Builder {
        return apply {
            addImport("androidx.lifecycle", "ViewModel", "viewModelScope")
            addImport("kotlinx.coroutines", "launch")
            addImport("kotlinx.coroutines.flow", "StateFlow", "Flow")

            when (metadata.diConfig.framework) {
                DependencyInjection.HILT -> {
                    addImport("dagger.hilt.android.lifecycle", "HiltViewModel")
                    addImport("javax.inject", "Inject")
                }

                DependencyInjection.KOIN -> {
                    addImport("org.koin.android.ext.android", "get")
                }

                else -> { /* No additional imports */
                }
            }
        }
    }

    /**
     * Adds iOS-specific imports to the file spec.
     */
    private fun FileSpec.Builder.addIosImports(): FileSpec.Builder {
        return apply {
            addImport("kotlinx.coroutines", "CoroutineScope", "launch", "runBlocking")
            addImport("kotlinx.coroutines.flow", "StateFlow", "Flow", "collect")
        }
    }

    /**
     * Adds common imports to the file spec.
     */
    private fun FileSpec.Builder.addCommonImports(): FileSpec.Builder {
        return apply {
            addImport("kotlinx.coroutines", "CoroutineScope")
            addImport("kotlinx.coroutines.flow", "StateFlow", "Flow")
        }
    }

    /**
     * Writes the generated file to the appropriate output directory.
     */
    private fun writeFile(fileSpec: FileSpec, metadata: MviMetadata, suffix: String = "") {
        try {
            val fileName = if (suffix.isNotEmpty()) {
                "${metadata.generationConfig.viewModelClassName}$suffix"
            } else {
                metadata.generationConfig.viewModelClassName
            }

            // Create the file using KSP CodeGenerator
            val file = codeGenerator.createNewFile(
                dependencies = Dependencies(false), // No dependencies on source files
                packageName = metadata.generationConfig.outputPackage,
                fileName = fileName
            )

            // Write the content to the file
            file.bufferedWriter().use { writer ->
                fileSpec.writeTo(writer)
            }

            logger.info("📝 FlowKit: Generated ViewModel: $fileName.kt")

        } catch (exception: Exception) {
            logger.error("❌ FlowKit: Failed to write ViewModel: ${exception.message}")
            throw exception
        }
    }
}
